name: Test
on: [push, pull_request]

env:
  GO_VERSION: 1.18
  GO_LINT_VERSION: v1.48.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version:  ${{ env.GO_VERSION }}

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run test 
      run: make test 

    - name: Lint code
      uses: golangci/golangci-lint-action@v2
      continue-on-error: true
      with:
        version: ${{ env.GO_LINT_VERSION }}
        args: --timeout 3m --verbose
