name: Test
on: [push, pull_request]
  # To make it possible to trigger e2e CI workflow for any arbitrary git ref
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.18
      uses: actions/setup-go@v2
      with:
        go-version: ^1.18

    - name: Check out code
      uses: actions/checkout@v2

    - name: Run test 
      run: make test 

    - name: Lint codes
      run: make lint
