name: Test
on: [push, pull_request]

env:
  GO_VERSION: "1.20"
  GO_LINT_VERSION: v1.48.0

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version:  ${{ env.GO_VERSION }}

    - name: Check out code
      uses: actions/checkout@v3

    - name: Run test 
      run: make test 

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version:  ${{ env.GO_VERSION }}
      - uses: actions/checkout@v3
      - name: Lint code
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ env.GO_LINT_VERSION }}
          args: --timeout 3m --verbose

